Bundler.require

require "gorillas/coordinates"
require "gorillas/bounding_box"
require "gorillas/velocity"
require "gorillas/banana"
require "gorillas/explosion"
require "gorillas/hole"
require "gorillas/house"
require "gorillas/house_collection"
require "gorillas/house_parameters_generator"
require "gorillas/gorilla"
require "gorillas/gorilla_collection"
require "gorillas/aiming_arrow"
require "gorillas/game_window"
require "gorillas/z_order"
require "gorillas/projectile_calculator"
require "gorillas/game_state"
